### ISSUE TITLE
Outdated GitHub Packages

### ISSUE THREAD

**Issue by saraedum** [JoeShook/ZiggyCreatures.FusionCache.Metrics#203]
The packages, e.g., https://github.com/JoeShook/ZiggyCreatures.FusionCache.Metrics/pkgs/nuget/ZiggyCreatures.FusionCache.Metrics.Core say `Published almost 2 years ago`.

I guess this package is actually only released to nuget currently? No big deal, but maybe the "packages" here on GitHub could be deleted if they are not updated anymore (at least to me this made the project look much less active than it actually is.)

**Comment by JoeShook** [comment]
Everything is on Nuget of course.  

I will try to take some time and see what I can do with this.

**Comment by JoeShook** [comment]
Deleted GitHub Packages
